// <auto-generated />
namespace ControleEstacionamento.Persistence.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class InserindoCamposMovimentacaoVeiculo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InserindoCamposMovimentacaoVeiculo));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191345020_InserindoCamposMovimentacaoVeiculo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
